spring:
  application:
    name: priceservice
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate.ddl-auto: update
    
    
  sql:
    init:
      mode: always
      platform: h2
  
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url: jdbc:h2:./db/basededatos
    username: sa
    password:
    driverClassName: org.h2.Driver
    
    
server:
 port : 8089
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  
  cloud:
    config:
      enable: true
      uri: http://localhost:8888
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
